import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.scss'
import { getSiteSettings } from '@/sanity/lib/queries'
import { InteractionProvider } from './context/InteractionContext'
import { PanelProvider } from './context/PanelContext'
import LenisProvider from './components/LenisProvider/LenisProvider'
import VideoBackground from './components/VideoBackground/VideoBackground'
import Logo from './components/Logo/Logo'
import Nav from './components/Nav/Nav'

const neueHaas = localFont({
  src: './fonts/NeueHaasDisplayRoman.ttf',
  variable: '--font-neue-haas',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const settings = await getSiteSettings()
  console.log(settings)

  return (
    <html lang="en" className={neueHaas.variable}>
      <body>
        <LenisProvider>
          <InteractionProvider>
            <PanelProvider>
              {settings?.backgroundVideoUrl && (
                <VideoBackground url={settings.backgroundVideoUrl} />
              )}
              {settings?.logoUrl && (
                <Logo url={settings.logoUrl} alt={settings.siteName} />
              )}
              <Nav reachOut={settings?.reachOut} checkWork={settings?.checkWork} description={settings?.description} info={settings?.info} />
              <main>
                {children}
              </main>
            </PanelProvider>
          </InteractionProvider>
        </LenisProvider>
      </body>
    </html>
  )
}
